// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

// Use environment variables for flexible configuration
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://riduqdqarirfqouazgwf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJpZHVxZHFhcmlyZnFvdWF6Z3dmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxMDQzODUsImV4cCI6MjA3NDY4MDM4NX0.sXrlOxHDKde3xo0aKIoIoPsuvEPIqIcvCIzwfegP4T0";

// Export the URL to allow other parts of the app to construct endpoints (e.g., webhooks)
export { SUPABASE_URL };

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);